DECLARE @SummaryOfChanges_Payment_Types TABLE ([Payment_Id] INT, [Action] VARCHAR(100));

MERGE INTO [Payment_Types] AS Target
USING (VALUES
		(2,N'Excess Learning Support: 16-18 Apprenticeships',0,N'Excess Learning Support',4,8),
		(3,N'Exceptional Learning Support: 16-18 Apprenticeships',0,N'Exceptional Learning Support',NULL,NULL),
		(4,N'Audit Adjustments: 16-18 Apprenticeships',0,N'Audit Adjustments',NULL,NULL),
		(5,N'Authorised Claims: 16-18 Apprenticeships',0,N'Authorised Claims',4,2),
		(6,N'Learner Support: 16-18 Apprenticeships',0,N'Learner Support',4,10),
		(7,N'Excess Learning Support: 19-23 Apprenticeships',0,N'Excess Learning Support',11,8),
		(8,N'Exceptional Learning Support: 19-23 Apprenticeships',0,N'Exceptional Learning Support',NULL,NULL),
		(9,N'Audit Adjustments: 19-23 Apprenticeships',0,N'Audit Adjustments',NULL,NULL),
		(10,N'Authorised Claims: 19-23 Apprenticeships',0,N'Authorised Claims',11,2),
		(11,N'Learner Support: 19-23 Apprenticeships',0,N'Learner Support',11,10),
		(12,N'Excess Learning Support: 24+ Apprenticeships',0,N'Excess Learning Support',15,8),
		(13,N'Exceptional Learning Support: 24+ Apprenticeships',0,N'Exceptional Learning Support',NULL,NULL),
		(14,N'Audit Adjustments: 24+ Apprenticeships',0,N'Audit Adjustments',NULL,NULL),
		(15,N'Authorised Claims: 24+ Apprenticeships',0,N'Authorised Claims',15,2),
		(16,N'Learner Support: 24+ Apprenticeships',0,N'Learner Support',15,10),
		(17,N'Authorised Claims: 16-18 Traineeships',0,N'Authorised Claims',6,2),
		(18,N'Audit Adjustments: 16-18 Traineeships',0,N'Audit Adjustments',NULL,NULL),
		(19,N'Excess Learning Support: 19-24 Traineeships',0,N'Excess Learning Support',13,8),
		(20,N'Exceptional Learning Support: 19-24 Traineeships',0,N'Exceptional Learning Support',NULL,NULL),
		(21,N'Audit Adjustments: 19-24 Traineeships',0,N'Audit Adjustments',NULL,NULL),
		(22,N'Authorised Claims: 19-24 Traineeships',0,N'Authorised Claims',13,2),
		(23,N'Learner Support: 19-24 Traineeships',0,N'Learner Support',13,10),
		(32,N'Vulnerable Bursary: 16-19 Traineeships Bursary',0,N'Vulnerable Bursary',6,12),
		(33,N'Discretionary Bursary: 16-19 Traineeships Bursary',0,N'Discretionary Bursary',6,7),
		(34,N'Free Meals: 16-19 Traineeships Bursary',0,N'Free Meals',6,9),
		(35,N'Excess Support: Advanced Learner Loans Bursary',0,N'Excess Learning Support',17,1),
		(36,N'Exceptional Learning Support: Advanced Learner Loans Bursary',0,N'Exceptional Learning Support',NULL,NULL),
		(37,N'Excess Learning Support: 16-18 Trailblazer Apprenticeships',0,N'Excess Learning Support',5,8),
		(38,N'Exceptional Learning Support: 16-18 Trailblazer Apprenticeships',0,N'Exceptional Learning Support',NULL,NULL),
		(39,N'Audit Adjustments: 16-18 Trailblazer Apprenticeships',0,N'Audit Adjustments',NULL,NULL),
		(40,N'Authorised Claims: 16-18 Trailblazer Apprenticeships',0,N'Authorised Claims',5,2),
		(42,N'Excess Learning Support: 19-23 Trailblazer Apprenticeships',0,N'Excess Learning Support',12,8),
		(43,N'Exceptional Learning Support: 19-23 Trailblazer Apprenticeships',0,N'Exceptional Learning Support',NULL,NULL),
		(44,N'Audit Adjustments: 19-23 Trailblazer Apprenticeships',0,N'Audit Adjustments',NULL,NULL),
		(45,N'Authorised Claims: 19-23 Trailblazer Apprenticeships',0,N'Authorised Claims',12,2),
		(47,N'Excess Learning Support: 24+ Trailblazer Apprenticeships',0,N'Excess Learning Support',16,8),
		(48,N'Exceptional Learning Support: 24+ Trailblazer Apprenticeships',0,N'Exceptional Learning Support',NULL,NULL),
		(49,N'Audit Adjustments: 24+ Trailblazer Apprenticeships',0,N'Audit Adjustments',NULL,NULL),
		(50,N'Authorised Claims: 24+ Trailblazer Apprenticeships',0,N'Authorised Claims',16,2),
		(51,N'Excess Learning Support: 16-18 Traineeships',0,N'Excess Learning Support',6,8),
		(52,N'Excess Learning Support: AEB-Other Learning',0,N'Excess Learning Support',18,8),
		(53,N'Exceptional Learning Support: AEB-Other Learning',0,N'Exceptional Learning Support',NULL,NULL),
		(54,N'Audit Adjustments: AEB-Other Learning',0,N'Audit Adjustments',NULL,NULL),
		(55,N'Authorised Claims: AEB-Other Learning',0,N'Authorised Claims',18,2),
		(56,N'Audit Adjustments: Advanced Learner Loans Bursary',0,N'Area Costs Audit Adjustments',NULL,NULL),
		(57,N'Audit Adjustments: 16-18 Levy Apprenticeships - Employer',1,N'Audit Adjustments',NULL,NULL),
		(58,N'Audit Adjustments: 16-18 Levy Apprenticeships - Provider',1,N'Audit Adjustments',NULL,NULL),
		(59,N'Audit Adjustments: 16-18 Levy Apprenticeships - Training',1,N'Audit Adjustments',NULL,NULL),
		(60,N'Audit Adjustments: 16-18 Non-Levy Apprenticeships - Employer',1,N'Audit Adjustments',NULL,NULL),
		(61,N'Audit Adjustments: 16-18 Non-Levy Apprenticeships - Provider',1,N'Audit Adjustments',NULL,NULL),
		(62,N'Audit Adjustments: 16-18 Non-Levy Apprenticeships - Training',1,N'Audit Adjustments',NULL,NULL),
		(63,N'Audit Adjustments: Adult Levy Apprenticeships - Employer',1,N'Audit Adjustments',NULL,NULL),
		(64,N'Audit Adjustments: Adult Levy Apprenticeships - Provider',1,N'Audit Adjustments',NULL,NULL),
		(65,N'Audit Adjustments: Adult Levy Apprenticeships - Training',1,N'Audit Adjustments',NULL,NULL),
		(66,N'Audit Adjustments: Adult Non-Levy Apprenticeships - Employer',1,N'Audit Adjustments',NULL,NULL),
		(67,N'Audit Adjustments: Adult Non-Levy Apprenticeships - Provider',1,N'Audit Adjustments',NULL,NULL),
		(68,N'Audit Adjustments: Adult Non-Levy Apprenticeships - Training',1,N'Audit Adjustments',NULL,NULL),
		(69,N'Authorised Claims: 16-18 Levy Apprenticeships - Employer',1,N'Authorised Claims',1,4),
		(70,N'Authorised Claims: 16-18 Levy Apprenticeships - Provider',1,N'Authorised Claims',1,5),
		(71,N'Authorised Claims: 16-18 Levy Apprenticeships - Training',1,N'Authorised Claims',1,6),
		(72,N'Authorised Claims: 16-18 Non-Levy Apprenticeships - Employer',1,N'Authorised Claims',2,4),
		(73,N'Authorised Claims: 16-18 Non-Levy Apprenticeships - Provider',1,N'Authorised Claims',2,5),
		(74,N'Authorised Claims: 16-18 Non-Levy Apprenticeships - Training',1,N'Authorised Claims',2,6),
		(75,N'Authorised Claims: Adult Levy Apprenticeships - Employer',1,N'Authorised Claims',8,4),
		(76,N'Authorised Claims: Adult Levy Apprenticeships - Provider',1,N'Authorised Claims',8,5),
		(77,N'Authorised Claims: Adult Levy Apprenticeships - Training',1,N'Authorised Claims',8,6),
		(78,N'Authorised Claims: Adult Non-Levy Apprenticeships - Employer',1,N'Authorised Claims',9,4),
		(79,N'Authorised Claims: Adult Non-Levy Apprenticeships - Provider',1,N'Authorised Claims',9,5),
		(80,N'Authorised Claims: Adult Non-Levy Apprenticeships - Training',1,N'Authorised Claims',9,6),
		(81,N'Excess Learning Support: 16-18 Levy Apprenticeships - Provider',1,N'Excess Learning Support',1,8),
		(82,N'Excess Learning Support: 16-18 Non-Levy Apprenticeships - Provider',1,N'Excess Learning Support',2,8),
		(83,N'Excess Learning Support: Adult Levy Apprenticeships - Provider',1,N'Excess Learning Support',8,8),
		(84,N'Excess Learning Support: Adult Non-Levy Apprenticeships - Provider',1,N'Excess Learning Support',9,8),
		(85,N'Exceptional Learning Support: 16-18 Levy Apprenticeships - Provider',1,N'Exceptional Learning Support',NULL,NULL),
		(86,N'Exceptional Learning Support: 16-18 Non-Levy Apprenticeships - Provider',1,N'Exceptional Learning Support',NULL,NULL),
		(87,N'Exceptional Learning Support: Adult Levy Apprenticeships - Provider',1,N'Exceptional Learning Support',NULL,NULL),
		(88,N'Exceptional Learning Support: Adult Non-Levy Apprenticeships - Provider',1,N'Exceptional Learning Support',NULL,NULL),
		(89,N'Audit Adjustments: Additional payments for employers',0,N'',NULL,NULL),
		(90,N'Audit Adjustments: Additional payments for providers',0,N'',NULL,NULL),
		(91,N'Audit Adjustments: Training (excluding English & Maths)',0,N'',NULL,NULL),
		(92,N'Authorised Claims: Additional payments for employers',0,N'',NULL,NULL),
		(93,N'Authorised Claims: Additional payments for providers',0,N'',NULL,NULL),
		(94,N'Authorised Claims: Training (excluding English & Maths)',0,N'',NULL,NULL),
		(95,N'Exceptional Learning Support: Additional payments for providers',0,N'',NULL,NULL),
		(96,N'Excess Learning Support: Additional payments for providers',0,N'',NULL,NULL),
		(97,N'Excess Learning Support: Advanced Learner Loans Bursary',0,N'',NULL,NULL),
		(100,N'Excess Learning Support: 16-18 Non-Levy Apprenticeships (procured) - Provider',1,N'Excess Learning Support',3,8),
		(101,N'Exceptional Learning Support: 16-18 Non-Levy Apprenticeships (procured) - Provider',1,N'Exceptional Learning Support',NULL,NULL),
		(102,N'Audit Adjustments: 16-18 Non-Levy Apprenticeships (procured) - Training',1,N'Audit Adjustments',NULL,NULL),
		(103,N'Audit Adjustments: 16-18 Non-Levy Apprenticeships (procured) - Provider',1,N'Audit Adjustments',NULL,NULL),
		(104,N'Audit Adjustments: 16-18 Non-Levy Apprenticeships (procured) - Employer',1,N'Audit Adjustments',NULL,NULL),
		(105,N'Authorised Claims: 16-18 Non-Levy Apprenticeships (procured) - Training',1,N'Authorised Claims',3,6),
		(106,N'Authorised Claims: 16-18 Non-Levy Apprenticeships (procured) - Provider',1,N'Authorised Claims',3,5),
		(107,N'Authorised Claims: 16-18 Non-Levy Apprenticeships (procured) - Employer',1,N'Authorised Claims',3,4),
		(108,N'Excess Learning Support: Adult Non-Levy Apprenticeships (procured) - Provider',1,N'Excess Learning Support',10,8),
		(109,N'Exceptional Learning Support: Adult Non-Levy Apprenticeships (procured) - Provider',1,N'Exceptional Learning Support',NULL,NULL),
		(110,N'Audit Adjustments: Adult Non-Levy Apprenticeships (procured) - Training',1,N'Audit Adjustments',NULL,NULL),
		(111,N'Audit Adjustments: Adult Non-Levy Apprenticeships (procured) - Provider',1,N'Audit Adjustments',NULL,NULL),
		(112,N'Audit Adjustments: Adult Non-Levy Apprenticeships (procured) - Employer',1,N'Audit Adjustments',NULL,NULL),
		(113,N'Authorised Claims: Adult Non-Levy Apprenticeships (procured) - Training',1,N'Authorised Claims',10,6),
		(114,N'Authorised Claims: Adult Non-Levy Apprenticeships (procured) - Provider',1,N'Authorised Claims',10,5),
		(115,N'Authorised Claims: Adult Non-Levy Apprenticeships (procured) - Employer',1,N'Authorised Claims',10,4),
		(116,N'Excess Learning Support: 19-24 Traineeships (From Nov 2017)',0,N'Excess Learning Support',14,8),
		(117,N'Exceptional Learning Support: 19-24 Traineeships (From Nov 2017)',0,N'Exceptional Learning Support',NULL,NULL),
		(118,N'Audit Adjustments: 19-24 Traineeships (From Nov 2017)',0,N'Audit Adjustments',NULL,NULL),
		(119,N'Authorised Claims: 19-24 Traineeships (From Nov 2017)',0,N'Authorised Claims',14,2),
		(120,N'Learner Support: 19-24 Traineeships (From Nov 2017)',0,N'Learner Support',14,10),
		(121,N'Excess Learning Support: AEB-Other Learning (From Nov 2017)',0,N'Excess Learning Support',19,8),
		(122,N'Exceptional Learning Support: AEB-Other Learning (From Nov 2017)',0,N'Exceptional Learning Support',NULL,NULL),
		(123,N'Audit Adjustments: AEB-Other Learning (From Nov 2017)',0,N'Audit Adjustments',NULL,NULL),
		(124,N'Authorised Claims: AEB-Other Learning (From Nov 2017)',0,N'Authorised Claims',19,2),
		(125,N'Audit Adjustments: 16-18 Levy Apprenticeships - Apprentice',1,N'',NULL,NULL),
		(126,N'Authorised Claims: 16-18 Levy Apprenticeships - Apprentice',1,N'',1,3),
		(127,N'Audit Adjustments: Adult Levy Apprenticeships - Apprentice',1,N'',NULL,NULL),
		(128,N'Authorised Claims: Adult Levy Apprenticeships - Apprentice',1,N'',8,3),
		(129,N'Audit Adjustments: 16-18 Non-Levy Apprenticeships (procured) - Apprentice',1,N'',NULL,NULL),
		(130,N'Authorised Claims: 16-18 Non-Levy Apprenticeships (procured) - Apprentice',1,N'',3,3),
		(131,N'Audit Adjustments: Adult Non-Levy Apprenticeships (procured) - Apprentice',1,N'',NULL,NULL),
		(132,N'Authorised Claims: Adult Non-Levy Apprenticeships (procured) - Apprentice',1,N'',10,3),
		(133,N'Princes Trust: AEB-Other Learning',0,N'',18,11),
		(134,N'Princes Trust: AEB-Other Learning (From Nov 2017)',0,N'',19,11),
		(135,N'Authorised Claims: Advanced Learner Loans Bursary',0,N'',17,2)
)
	AS Source([Payment_Id], [PaymentName], [FM36], [PaymentTypeDescription],[FundinglineId],[AdjustmentTypeId])
	ON Target.[Payment_Id] = Source.[Payment_Id]
	WHEN MATCHED 
			AND EXISTS 
				(		SELECT Target.[Payment_Id] ,
							Target.[PaymentName] ,
							Target.[FM36] ,							
							Target.[PaymentTypeDescription] ,														  
							Target.[FundinglineId] ,  
							Target.[AdjustmentTypeId] 														  
					EXCEPT 
						SELECT Source.[Payment_Id] ,
							Source.[PaymentName]	,
							Source.[FM36] ,							
							Source.[PaymentTypeDescription] ,														  
							Source.[FundinglineId] ,  
							Source.[AdjustmentTypeId] 					      
				)
		  THEN UPDATE SET 
						Target.[Payment_Id] = Source.[Payment_Id],
						Target.[PaymentName] = Source.[PaymentName],
						Target.[FM36] = Source.[FM36],						
						Target.[PaymentTypeDescription] = Source.[PaymentTypeDescription],
						Target.[FundinglineId] = Source.[FundinglineId],
						Target.[AdjustmentTypeId] = Source.[AdjustmentTypeId]
	WHEN NOT MATCHED BY TARGET THEN INSERT([Payment_Id], [PaymentName], [FM36], [PaymentTypeDescription],[FundinglineId],[AdjustmentTypeId]) 
									VALUES ([Payment_Id], [PaymentName], [FM36], [PaymentTypeDescription],[FundinglineId],[AdjustmentTypeId])
	WHEN NOT MATCHED BY SOURCE THEN DELETE
	OUTPUT Inserted.[Payment_Id],$action INTO @SummaryOfChanges_Payment_Types([Payment_Id],[Action])
;


	DECLARE @AddCount_AET INT, @UpdateCount_AET INT, @DeleteCount_AET INT
	SET @AddCount_AET  = ISNULL((SELECT Count(*) FROM @SummaryOfChanges_Payment_Types WHERE [Action] = 'Insert' GROUP BY Action),0);
	SET @UpdateCount_AET = ISNULL((SELECT Count(*) FROM @SummaryOfChanges_Payment_Types WHERE [Action] = 'Update' GROUP BY Action),0);
	SET @DeleteCount_AET = ISNULL((SELECT Count(*) FROM @SummaryOfChanges_Payment_Types WHERE [Action] = 'Delete' GROUP BY Action),0);

	RAISERROR('		      %s - Added %i - Update %i - Delete %i',10,1,'AuditEventType', @AddCount_AET, @UpdateCount_AET, @DeleteCount_AET) WITH NOWAIT;

