DECLARE @SummaryOfChanges_Payment_Types TABLE ([Payment_Id] INT, [Action] VARCHAR(100));

MERGE INTO [Payment_Types] AS Target
USING (VALUES
		(2, N'Excess Learning Support: 16-18 Apprenticeships', 0, NULL, N'16-18 Apprenticeship Frameworks', N'Excess Learning Support', N'16-18 Apprenticeships', N'Excess Learning Support'),
(3, N'Exceptional Learning Support: 16-18 Apprenticeships', 0, NULL, N'16-18 Apprenticeship Frameworks', N'Exceptional Learning Support', NULL, NULL),
(4, N'Audit Adjustments: 16-18 Apprenticeships', 0, NULL, N'16-18 Apprenticeship Frameworks', N'Audit Adjustments', NULL, NULL),
(5, N'Authorised Claims: 16-18 Apprenticeships', 0, NULL, N'16-18 Apprenticeship Frameworks', N'Authorised Claims', N'16-18 Apprenticeships', N'Authorised Claims'),
(6, N'Learner Support: 16-18 Apprenticeships', 0, NULL, N'16-18 Apprenticeship Frameworks', N'Learner Support', N'16-18 Apprenticeships', N'Learner Support'),
(7, N'Excess Learning Support: 19-23 Apprenticeships', 0, NULL, N'19-23 Apprenticeship Frameworks', N'Excess Learning Support', N'19-23 Apprenticeships', N'Excess Learning Support'),
(8, N'Exceptional Learning Support: 19-23 Apprenticeships', 0, NULL, N'19-23 Apprenticeship Frameworks', N'Exceptional Learning Support', NULL, NULL),
(9, N'Audit Adjustments: 19-23 Apprenticeships', 0, NULL, N'19-23 Apprenticeship Frameworks', N'Audit Adjustments', NULL, NULL),
(10, N'Authorised Claims: 19-23 Apprenticeships', 0, NULL, N'19-23 Apprenticeship Frameworks', N'Authorised Claims', N'19-23 Apprenticeships', N'Authorised Claims'),
(11, N'Learner Support: 19-23 Apprenticeships', 0, NULL, N'19-23 Apprenticeship Frameworks', N'Learner Support', N'19-23 Apprenticeships', N'Learner Support'),
(12, N'Excess Learning Support: 24+ Apprenticeships', 0, NULL, N'24+ Apprenticeship Frameworks', N'Excess Learning Support', N'24+ Apprenticeships', N'Excess Learning Support'),
(13, N'Exceptional Learning Support: 24+ Apprenticeships', 0, NULL, N'24+ Apprenticeship Frameworks', N'Exceptional Learning Support', NULL, NULL),
(14, N'Audit Adjustments: 24+ Apprenticeships', 0, NULL, N'24+ Apprenticeship Frameworks', N'Audit Adjustments', NULL, NULL),
(15, N'Authorised Claims: 24+ Apprenticeships', 0, NULL, N'24+ Apprenticeship Frameworks', N'Authorised Claims', N'24+ Apprenticeships', N'Authorised Claims'),
(16, N'Learner Support: 24+ Apprenticeships', 0, NULL, N'24+ Apprenticeship Frameworks', N'Learner Support', N'24+ Apprenticeships', N'Learner Support'),
(17, N'Authorised Claims: 16-18 Traineeships', 0, NULL, N'16-18 Traineeships', N'Authorised Claims', N'16-18 Traineeships', N'Authorised Claims'),
(18, N'Audit Adjustments: 16-18 Traineeships', 0, NULL, N'16-18 Traineeships', N'Audit Adjustments', NULL, NULL),
(19, N'Excess Learning Support: 19-24 Traineeships', 0, N'Adult Education - Non-procured delivery', N'19-24 Traineeships', N'Excess Learning Support', N'19-24 Traineeships (non-procured)', N'Excess Learning Support'),
(20, N'Exceptional Learning Support: 19-24 Traineeships', 0, N'Adult Education - Non-procured delivery', N'19-24 Traineeships', N'Exceptional Learning Support', NULL, NULL),
(21, N'Audit Adjustments: 19-24 Traineeships', 0, N'Adult Education - Non-procured delivery', N'19-24 Traineeships', N'Audit Adjustments', NULL, NULL),
(22, N'Authorised Claims: 19-24 Traineeships', 0, N'Adult Education - Non-procured delivery', N'19-24 Traineeships', N'Authorised Claims', N'19-24 Traineeships (non-procured)', N'Authorised Claims'),
(23, N'Learner Support: 19-24 Traineeships', 0, N'Adult Education - Non-procured delivery', N'19-24 Traineeships', N'Learner Support', N'19-24 Traineeships (non-procured)', N'Learner Support'),
(32, N'Vulnerable Bursary: 16-19 Traineeships Bursary', 0, NULL, N'16-19 Traineeships Bursary', N'Vulnerable Bursary', N'16-19 Traineeships Bursary', N'Vulnerable Bursary'),
(33, N'Discretionary Bursary: 16-19 Traineeships Bursary', 0, NULL, N'16-19 Traineeships Bursary', N'Discretionary Bursary', N'16-19 Traineeships Bursary', N'Discretionary Bursary'),
(34, N'Free Meals: 16-19 Traineeships Bursary', 0, NULL, N'16-19 Traineeships Bursary', N'Free Meals', N'16-19 Traineeships Bursary', N'Free Meals'),
(35, N'Excess Support: Advanced Learner Loans Bursary', 0, NULL, N'Advanced Learner Loans Bursary', N'Excess Learning Support', N'Advanced Learner Loans Bursary', N'ALLB Excess Support'),
(36, N'Exceptional Learning Support: Advanced Learner Loans Bursary', 0, NULL, N'Advanced Learner Loans Bursary', N'Exceptional Learning Support', NULL, NULL),
(37, N'Excess Learning Support: 16-18 Trailblazer Apprenticeships', 0, NULL, N'16-18 Trailblazer Apprenticeships ', N'Excess Learning Support', N'16-18 Trailblazer Apprenticeships', N'Excess Learning Support'),
(38, N'Exceptional Learning Support: 16-18 Trailblazer Apprenticeships', 0, NULL, N'16-18 Trailblazer Apprenticeships ', N'Exceptional Learning Support', NULL, NULL),
(39, N'Audit Adjustments: 16-18 Trailblazer Apprenticeships', 0, NULL, N'16-18 Trailblazer Apprenticeships ', N'Audit Adjustments', NULL, NULL),
(40, N'Authorised Claims: 16-18 Trailblazer Apprenticeships', 0, NULL, N'16-18 Trailblazer Apprenticeships ', N'Authorised Claims', N'16-18 Trailblazer Apprenticeships', N'Authorised Claims'),
(42, N'Excess Learning Support: 19-23 Trailblazer Apprenticeships', 0, NULL, N'19-23 Trailblazer Apprenticeships', N'Excess Learning Support', N'19-23 Trailblazer Apprenticeships', N'Excess Learning Support'),
(43, N'Exceptional Learning Support: 19-23 Trailblazer Apprenticeships', 0, NULL, N'19-23 Trailblazer Apprenticeships', N'Exceptional Learning Support', NULL, NULL),
(44, N'Audit Adjustments: 19-23 Trailblazer Apprenticeships', 0, NULL, N'19-23 Trailblazer Apprenticeships', N'Audit Adjustments', NULL, NULL),
(45, N'Authorised Claims: 19-23 Trailblazer Apprenticeships', 0, NULL, N'19-23 Trailblazer Apprenticeships', N'Authorised Claims', N'19-23 Trailblazer Apprenticeships', N'Authorised Claims'),
(47, N'Excess Learning Support: 24+ Trailblazer Apprenticeships', 0, NULL, N'24+ Trailblazer Apprenticeships', N'Excess Learning Support', N'24+ Trailblazer Apprenticeships', N'Excess Learning Support'),
(48, N'Exceptional Learning Support: 24+ Trailblazer Apprenticeships', 0, NULL, N'24+ Trailblazer Apprenticeships', N'Exceptional Learning Support', NULL, NULL),
(49, N'Audit Adjustments: 24+ Trailblazer Apprenticeships', 0, NULL, N'24+ Trailblazer Apprenticeships', N'Audit Adjustments', NULL, NULL),
(50, N'Authorised Claims: 24+ Trailblazer Apprenticeships', 0, NULL, N'24+ Trailblazer Apprenticeships', N'Authorised Claims', N'24+ Trailblazer Apprenticeships', N'Authorised Claims'),
(51, N'Excess Learning Support: 16-18 Traineeships', 0, NULL, N'16-18 Traineeships', N'Excess Learning Support', N'16-18 Traineeships', N'Excess Learning Support'),
(52, N'Excess Learning Support: AEB-Other Learning', 0, N'Adult Education - Non-procured delivery', N'AEB - Other Learning ', N'Excess Learning Support', N'AEB - Other Learning (non-procured)', N'Excess Learning Support'),
(53, N'Exceptional Learning Support: AEB-Other Learning', 0, N'Adult Education - Non-procured delivery', N'AEB - Other Learning ', N'Exceptional Learning Support', NULL, NULL),
(54, N'Audit Adjustments: AEB-Other Learning', 0, N'Adult Education - Non-procured delivery', N'AEB - Other Learning ', N'Audit Adjustments', NULL, NULL),
(55, N'Authorised Claims: AEB-Other Learning', 0, N'Adult Education - Non-procured delivery', N'AEB - Other Learning ', N'Authorised Claims', N'AEB - Other Learning (non-procured)', N'Authorised Claims'),
(56, N'Audit Adjustments: Advanced Learner Loans Bursary', 0, NULL, N'Advanced Learner Loans Bursary', N'Area Costs Audit Adjustments', NULL, NULL),
(57, N'Audit Adjustments: 16-18 Levy Apprenticeships - Employer', 1, N'16-18 Levy contracted Apprenticeships', N'Additional payments for employers', N'Audit Adjustments', NULL, NULL),
(58, N'Audit Adjustments: 16-18 Levy Apprenticeships - Provider', 1, N'16-18 Levy contracted Apprenticeships', N'Additional payments for providers', N'Audit Adjustments', NULL, NULL),
(59, N'Audit Adjustments: 16-18 Levy Apprenticeships - Training', 1, N'16-18 Levy contracted Apprenticeships', N'Training (excluding English & Maths)', N'Audit Adjustments', NULL, NULL),
(60, N'Audit Adjustments: 16-18 Non-Levy Apprenticeships - Employer', 1, N'16-18 Non-levy contracted Apprenticeships - Non-procured delivery', N'Additional payments for employers', N'Audit Adjustments', NULL, NULL),
(61, N'Audit Adjustments: 16-18 Non-Levy Apprenticeships - Provider', 1, N'16-18 Non-levy contracted Apprenticeships - Non-procured delivery', N'Additional payments for providers', N'Audit Adjustments', NULL, NULL),
(62, N'Audit Adjustments: 16-18 Non-Levy Apprenticeships - Training', 1, N'16-18 Non-levy contracted Apprenticeships - Non-procured delivery', N'Training (excluding English & Maths)', N'Audit Adjustments', NULL, NULL),
(63, N'Audit Adjustments: Adult Levy Apprenticeships - Employer', 1, N'Adult Levy contracted Apprenticeships', N'Additional payments for employers', N'Audit Adjustments', NULL, NULL),
(64, N'Audit Adjustments: Adult Levy Apprenticeships - Provider', 1, N'Adult Levy contracted Apprenticeships', N'Additional payments for providers', N'Audit Adjustments', NULL, NULL),
(65, N'Audit Adjustments: Adult Levy Apprenticeships - Training', 1, N'Adult Levy contracted Apprenticeships', N'Training (excluding English & Maths)', N'Audit Adjustments', NULL, NULL),
(66, N'Audit Adjustments: Adult Non-Levy Apprenticeships - Employer', 1, N'Adult Non-levy contracted Apprenticeships - Non-procured delivery', N'Additional payments for employers', N'Audit Adjustments', NULL, NULL),
(67, N'Audit Adjustments: Adult Non-Levy Apprenticeships - Provider', 1, N'Adult Non-levy contracted Apprenticeships - Non-procured delivery', N'Additional payments for providers', N'Audit Adjustments', NULL, NULL),
(68, N'Audit Adjustments: Adult Non-Levy Apprenticeships - Training', 1, N'Adult Non-levy contracted Apprenticeships - Non-procured delivery', N'Training (excluding English & Maths)', N'Audit Adjustments', NULL, NULL),
(69, N'Authorised Claims: 16-18 Levy Apprenticeships - Employer', 1, N'16-18 Levy contracted Apprenticeships', N'Additional payments for employers', N'Authorised Claims', N'16-18 Apprenticeship (From May 2017) Levy Contract', N'Authorised Claims - Additional payments for employer'),
(70, N'Authorised Claims: 16-18 Levy Apprenticeships - Provider', 1, N'16-18 Levy contracted Apprenticeships', N'Additional payments for providers', N'Authorised Claims', N'16-18 Apprenticeship (From May 2017) Levy Contract', N'Authorised Claims - Additional payments for provider'),
(71, N'Authorised Claims: 16-18 Levy Apprenticeships - Training', 1, N'16-18 Levy contracted Apprenticeships', N'Training (excluding English & Maths)', N'Authorised Claims', N'16-18 Apprenticeship (From May 2017) Levy Contract', N'Authorised Claims - Training costs exc Maths/Eng'),
(72, N'Authorised Claims: 16-18 Non-Levy Apprenticeships - Employer', 1, N'16-18 Non-levy contracted Apprenticeships - Non-procured delivery', N'Additional payments for employers', N'Authorised Claims', N'16-18 Apprenticeship (From May 2017) Non-Levy Contract (non-procured)', N'Authorised Claims - Additional payments for employer'),
(73, N'Authorised Claims: 16-18 Non-Levy Apprenticeships - Provider', 1, N'16-18 Non-levy contracted Apprenticeships - Non-procured delivery', N'Additional payments for providers', N'Authorised Claims', N'16-18 Apprenticeship (From May 2017) Non-Levy Contract (non-procured)', N'Authorised Claims - Additional payments for provider'),
(74, N'Authorised Claims: 16-18 Non-Levy Apprenticeships - Training', 1, N'16-18 Non-levy contracted Apprenticeships - Non-procured delivery', N'Training (excluding English & Maths)', N'Authorised Claims', N'16-18 Apprenticeship (From May 2017) Non-Levy Contract (non-procured)', N'Authorised Claims - Training costs exc Maths/Eng'),
(75, N'Authorised Claims: Adult Levy Apprenticeships - Employer', 1, N'Adult Levy contracted Apprenticeships', N'Additional payments for employers', N'Authorised Claims', N'19+ Apprenticeship (From May 2017) Levy Contract', N'Authorised Claims - Additional payments for employer'),
(76, N'Authorised Claims: Adult Levy Apprenticeships - Provider', 1, N'Adult Levy contracted Apprenticeships', N'Additional payments for providers', N'Authorised Claims', N'19+ Apprenticeship (From May 2017) Levy Contract', N'Authorised Claims - Additional payments for provider'),
(77, N'Authorised Claims: Adult Levy Apprenticeships - Training', 1, N'Adult Levy contracted Apprenticeships', N'Training (excluding English & Maths)', N'Authorised Claims', N'19+ Apprenticeship (From May 2017) Levy Contract', N'Authorised Claims - Training costs exc Maths/Eng'),
(78, N'Authorised Claims: Adult Non-Levy Apprenticeships - Employer', 1, N'Adult Non-levy contracted Apprenticeships - Non-procured delivery', N'Additional payments for employers', N'Authorised Claims', N'19+ Apprenticeship (From May 2017) Non-Levy Contract (non-procured)', N'Authorised Claims - Additional payments for employer'),
(79, N'Authorised Claims: Adult Non-Levy Apprenticeships - Provider', 1, N'Adult Non-levy contracted Apprenticeships - Non-procured delivery', N'Additional payments for providers', N'Authorised Claims', N'19+ Apprenticeship (From May 2017) Non-Levy Contract (non-procured)', N'Authorised Claims - Additional payments for provider'),
(80, N'Authorised Claims: Adult Non-Levy Apprenticeships - Training', 1, N'Adult Non-levy contracted Apprenticeships - Non-procured delivery', N'Training (excluding English & Maths)', N'Authorised Claims', N'19+ Apprenticeship (From May 2017) Non-Levy Contract (non-procured)', N'Authorised Claims - Training costs exc Maths/Eng'),
(81, N'Excess Learning Support: 16-18 Levy Apprenticeships - Provider', 1, N'16-18 Levy contracted Apprenticeships', N'Additional payments for providers', N'Excess Learning Support', N'16-18 Apprenticeship (From May 2017) Levy Contract', N'Excess Learning Support'),
(82, N'Excess Learning Support: 16-18 Non-Levy Apprenticeships - Provider', 1, N'16-18 Non-levy contracted Apprenticeships - Non-procured delivery', N'Additional payments for providers', N'Excess Learning Support', N'16-18 Apprenticeship (From May 2017) Non-Levy Contract (non-procured)', N'Excess Learning Support'),
(83, N'Excess Learning Support: Adult Levy Apprenticeships - Provider', 1, N'Adult Levy contracted Apprenticeships', N'Additional payments for providers', N'Excess Learning Support', N'19+ Apprenticeship (From May 2017) Levy Contract', N'Excess Learning Support'),
(84, N'Excess Learning Support: Adult Non-Levy Apprenticeships - Provider', 1, N'Adult Non-levy contracted Apprenticeships - Non-procured delivery', N'Additional payments for providers', N'Excess Learning Support', N'19+ Apprenticeship (From May 2017) Non-Levy Contract (non-procured)', N'Excess Learning Support'),
(85, N'Exceptional Learning Support: 16-18 Levy Apprenticeships - Provider', 1, N'16-18 Levy contracted Apprenticeships', N'Additional payments for providers', N'Exceptional Learning Support', NULL, NULL),
(86, N'Exceptional Learning Support: 16-18 Non-Levy Apprenticeships - Provider', 1, N'16-18 Non-levy contracted Apprenticeships - Non-procured delivery', N'Additional payments for providers', N'Exceptional Learning Support', NULL, NULL),
(87, N'Exceptional Learning Support: Adult Levy Apprenticeships - Provider', 1, N'Adult Levy contracted Apprenticeships', N'Additional payments for providers', N'Exceptional Learning Support', NULL, NULL),
(88, N'Exceptional Learning Support: Adult Non-Levy Apprenticeships - Provider', 1, N'Adult Non-levy contracted Apprenticeships - Non-procured delivery', N'Additional payments for providers', N'Exceptional Learning Support', NULL, NULL),
(89, N'Audit Adjustments: Additional payments for employers', 0, NULL, NULL, NULL, NULL, NULL),
(90, N'Audit Adjustments: Additional payments for providers', 0, NULL, NULL, NULL, NULL, NULL),
(91, N'Audit Adjustments: Training (excluding English & Maths)', 0, NULL, NULL, NULL, NULL, NULL),
(92, N'Authorised Claims: Additional payments for employers', 0, NULL, NULL, NULL, NULL, NULL),
(93, N'Authorised Claims: Additional payments for providers', 0, NULL, NULL, NULL, NULL, NULL),
(94, N'Authorised Claims: Training (excluding English & Maths)', 0, NULL, NULL, NULL, NULL, NULL),
(95, N'Exceptional Learning Support: Additional payments for providers', 0, NULL, NULL, NULL, NULL, NULL),
(96, N'Excess Learning Support: Additional payments for providers', 0, NULL, NULL, NULL, NULL, NULL),
(97, N'Excess Learning Support: Advanced Learner Loans Bursary', 0, NULL, NULL, NULL, NULL, NULL),
(100, N'Excess Learning Support: 16-18 Non-Levy Apprenticeships (procured) - Provider', 1, N'16-18 Non-levy contracted Apprenticeships - Procured delivery', N'Additional payments for providers', N'Excess Learning Support', N'16-18 Apprenticeship Non-Levy Contract (procured)', N'Excess Learning Support'),
(101, N'Exceptional Learning Support: 16-18 Non-Levy Apprenticeships (procured) - Provider', 1, N'16-18 Non-levy contracted Apprenticeships - Procured delivery', N'Additional payments for providers', N'Exceptional Learning Support', NULL, NULL),
(102, N'Audit Adjustments: 16-18 Non-Levy Apprenticeships (procured) - Training', 1, N'16-18 Non-levy contracted Apprenticeships - Procured delivery', N'Training (excluding English & Maths)', N'Audit Adjustments', NULL, NULL),
(103, N'Audit Adjustments: 16-18 Non-Levy Apprenticeships (procured) - Provider', 1, N'16-18 Non-levy contracted Apprenticeships - Procured delivery', N'Additional payments for providers', N'Audit Adjustments', NULL, NULL),
(104, N'Audit Adjustments: 16-18 Non-Levy Apprenticeships (procured) - Employer', 1, N'16-18 Non-levy contracted Apprenticeships - Procured delivery', N'Additional payments for employers', N'Audit Adjustments', NULL, NULL),
(105, N'Authorised Claims: 16-18 Non-Levy Apprenticeships (procured) - Training', 1, N'16-18 Non-levy contracted Apprenticeships - Procured delivery', N'Training (excluding English & Maths)', N'Authorised Claims', N'16-18 Apprenticeship Non-Levy Contract (procured)', N'Authorised Claims - Training costs exc Maths/Eng'),
(106, N'Authorised Claims: 16-18 Non-Levy Apprenticeships (procured) - Provider', 1, N'16-18 Non-levy contracted Apprenticeships - Procured delivery', N'Additional payments for providers', N'Authorised Claims', N'16-18 Apprenticeship Non-Levy Contract (procured)', N'Authorised Claims - Additional payments for provider'),
(107, N'Authorised Claims: 16-18 Non-Levy Apprenticeships (procured) - Employer', 1, N'16-18 Non-levy contracted Apprenticeships - Procured delivery', N'Additional payments for employers', N'Authorised Claims', N'16-18 Apprenticeship Non-Levy Contract (procured)', N'Authorised Claims - Additional payments for employer'),
(108, N'Excess Learning Support: Adult Non-Levy Apprenticeships (procured) - Provider', 1, N'Adult Non-levy contracted Apprenticeships - Procured delivery', N'Additional payments for providers', N'Excess Learning Support', N'19+ Apprenticeship Non-Levy Contract (procured)', N'Excess Learning Support'),
(109, N'Exceptional Learning Support: Adult Non-Levy Apprenticeships (procured) - Provider', 1, N'Adult Non-levy contracted Apprenticeships - Procured delivery', N'Additional payments for providers', N'Exceptional Learning Support', NULL, NULL),
(110, N'Audit Adjustments: Adult Non-Levy Apprenticeships (procured) - Training', 1, N'Adult Non-levy contracted Apprenticeships - Procured delivery', N'Training (excluding English & Maths)', N'Audit Adjustments', NULL, NULL),
(111, N'Audit Adjustments: Adult Non-Levy Apprenticeships (procured) - Provider', 1, N'Adult Non-levy contracted Apprenticeships - Procured delivery', N'Additional payments for providers', N'Audit Adjustments', NULL, NULL),
(112, N'Audit Adjustments: Adult Non-Levy Apprenticeships (procured) - Employer', 1, N'Adult Non-levy contracted Apprenticeships - Procured delivery', N'Additional payments for employers', N'Audit Adjustments', NULL, NULL),
(113, N'Authorised Claims: Adult Non-Levy Apprenticeships (procured) - Training', 1, N'Adult Non-levy contracted Apprenticeships - Procured delivery', N'Training (excluding English & Maths)', N'Authorised Claims', N'19+ Apprenticeship Non-Levy Contract (procured)', N'Authorised Claims - Training costs exc Maths/Eng'),
(114, N'Authorised Claims: Adult Non-Levy Apprenticeships (procured) - Provider', 1, N'Adult Non-levy contracted Apprenticeships - Procured delivery', N'Additional payments for providers', N'Authorised Claims', N'19+ Apprenticeship Non-Levy Contract (procured)', N'Authorised Claims - Additional payments for provider'),
(115, N'Authorised Claims: Adult Non-Levy Apprenticeships (procured) - Employer', 1, N'Adult Non-levy contracted Apprenticeships - Procured delivery', N'Additional payments for employers', N'Authorised Claims', N'19+ Apprenticeship Non-Levy Contract (procured)', N'Authorised Claims - Additional payments for employer'),
(116, N'Excess Learning Support: 19-24 Traineeships (From Nov 2017)', 0, N'Adult Education - Procured delivery from 1 Nov 2017', N'19-24 Traineeships', N'Excess Learning Support', N'19-24 Traineeships (procured from Nov 2017)', N'Excess Learning Support'),
(117, N'Exceptional Learning Support: 19-24 Traineeships (From Nov 2017)', 0, N'Adult Education - Procured delivery from 1 Nov 2017', N'19-24 Traineeships', N'Exceptional Learning Support', NULL, NULL),
(118, N'Audit Adjustments: 19-24 Traineeships (From Nov 2017)', 0, N'Adult Education - Procured delivery from 1 Nov 2017', N'19-24 Traineeships', N'Audit Adjustments', NULL, NULL),
(119, N'Authorised Claims: 19-24 Traineeships (From Nov 2017)', 0, N'Adult Education - Procured delivery from 1 Nov 2017', N'19-24 Traineeships', N'Authorised Claims', N'19-24 Traineeships (procured from Nov 2017)', N'Authorised Claims'),
(120, N'Learner Support: 19-24 Traineeships (From Nov 2017)', 0, N'Adult Education - Procured delivery from 1 Nov 2017', N'19-24 Traineeships', N'Learner Support', N'19-24 Traineeships (procured from Nov 2017)', N'Learner Support'),
(121, N'Excess Learning Support: AEB-Other Learning (From Nov 2017)', 0, N'Adult Education - Procured delivery from 1 Nov 2017', N'AEB - Other Learning ', N'Excess Learning Support', N'AEB - Other Learning (procured from Nov 2017)', N'Excess Learning Support'),
(122, N'Exceptional Learning Support: AEB-Other Learning (From Nov 2017)', 0, N'Adult Education - Procured delivery from 1 Nov 2017', N'AEB - Other Learning ', N'Exceptional Learning Support', NULL, NULL),
(123, N'Audit Adjustments: AEB-Other Learning (From Nov 2017)', 0, N'Adult Education - Procured delivery from 1 Nov 2017', N'AEB - Other Learning ', N'Audit Adjustments', NULL, NULL),
(124, N'Authorised Claims: AEB-Other Learning (From Nov 2017)', 0, N'Adult Education - Procured delivery from 1 Nov 2017', N'AEB - Other Learning ', N'Authorised Claims', N'AEB - Other Learning (procured from Nov 2017)', N'Authorised Claims'),
(125, N'Audit Adjustments: 16-18 Levy Apprenticeships - Apprentice', 1, NULL, NULL, NULL, NULL, NULL),
(126, N'Authorised Claims: 16-18 Levy Apprenticeships - Apprentice', 1, NULL, NULL, NULL, N'16-18 Apprenticeship (From May 2017) Levy Contract', N'Authorised Claims - Additional payments for apprentice'),
(127, N'Audit Adjustments: Adult Levy Apprenticeships - Apprentice', 1, NULL, NULL, NULL, NULL, NULL),
(128, N'Authorised Claims: Adult Levy Apprenticeships - Apprentice', 1, NULL, NULL, NULL, N'19+ Apprenticeship (From May 2017) Levy Contract', N'Authorised Claims - Additional payments for apprentice'),
(129, N'Audit Adjustments: 16-18 Non-Levy Apprenticeships (procured) - Apprentice', 1, NULL, NULL, NULL, NULL, NULL),
(130, N'Authorised Claims: 16-18 Non-Levy Apprenticeships (procured) - Apprentice', 1, NULL, NULL, NULL, N'16-18 Apprenticeship Non-Levy Contract (procured)', N'Authorised Claims - Additional payments for apprentice'),
(131, N'Audit Adjustments: Adult Non-Levy Apprenticeships (procured) - Apprentice', 1, NULL, NULL, NULL, NULL, NULL),
(132, N'Authorised Claims: Adult Non-Levy Apprenticeships (procured) - Apprentice', 1, NULL, NULL, NULL, N'19+ Apprenticeship Non-Levy Contract (procured)', N'Authorised Claims - Additional payments for apprentice'),
(133, N'Princes Trust: AEB-Other Learning', 0, NULL, NULL, NULL, N'AEB - Other Learning (non-procured)', N'Princes Trust'),
(134, N'Princes Trust: AEB-Other Learning (From Nov 2017)', 0, NULL, NULL, NULL, N'AEB - Other Learning (procured from Nov 2017)', N'Princes Trust'),
(135, N'Authorised Claims: Advanced Learner Loans Bursary', 0, NULL, NULL, NULL, N'Advanced Learner Loans Bursary', N'Authorised Claims') 
)
	AS Source([Payment_Id], [PaymentName], [FM36], [SubSectionHeading], [RowHeading], [PaymentTypeDescription],[Fundingline],[AdjustmentType])
	ON Target.[Payment_Id] = Source.[Payment_Id]
	WHEN MATCHED 
			AND EXISTS 
				(		SELECT Target.[Payment_Id] ,
							Target.[PaymentName] ,
							Target.[FM36] ,
							Target.[SubSectionHeading] ,
							Target.[RowHeading] ,
							Target.[PaymentTypeDescription] ,														  
							Target.[Fundingline] ,  
							Target.[AdjustmentType] 														  
					EXCEPT 
						SELECT Source.[Payment_Id] ,
							Source.[PaymentName]	,
							Source.[FM36] ,
							Source.[SubSectionHeading] ,
							Source.[RowHeading] ,
							Source.[PaymentTypeDescription] ,														  
							Source.[Fundingline] ,  
							Source.[AdjustmentType] 					      
				)
		  THEN UPDATE SET 
						Target.[Payment_Id] = Source.[Payment_Id],
						Target.[PaymentName] = Source.[PaymentName],
						Target.[FM36] = Source.[FM36],
						Target.[SubSectionHeading] = Source.[SubSectionHeading],
						Target.[RowHeading] = Source.[RowHeading],
						Target.[PaymentTypeDescription] = Source.[PaymentTypeDescription],
						Target.[Fundingline] = Source.[Fundingline],
						Target.[AdjustmentType] = Source.[AdjustmentType]
	WHEN NOT MATCHED BY TARGET THEN INSERT([Payment_Id], [PaymentName], [FM36], [SubSectionHeading], [RowHeading], [PaymentTypeDescription],[Fundingline],[AdjustmentType]) 
									VALUES ([Payment_Id], [PaymentName], [FM36], [SubSectionHeading], [RowHeading], [PaymentTypeDescription],[Fundingline],[AdjustmentType])
	WHEN NOT MATCHED BY SOURCE THEN DELETE
	OUTPUT Inserted.[Payment_Id],$action INTO @SummaryOfChanges_Payment_Types([Payment_Id],[Action])
;


	DECLARE @AddCount_AET INT, @UpdateCount_AET INT, @DeleteCount_AET INT
	SET @AddCount_AET  = ISNULL((SELECT Count(*) FROM @SummaryOfChanges_Payment_Types WHERE [Action] = 'Insert' GROUP BY Action),0);
	SET @UpdateCount_AET = ISNULL((SELECT Count(*) FROM @SummaryOfChanges_Payment_Types WHERE [Action] = 'Update' GROUP BY Action),0);
	SET @DeleteCount_AET = ISNULL((SELECT Count(*) FROM @SummaryOfChanges_Payment_Types WHERE [Action] = 'Delete' GROUP BY Action),0);

	RAISERROR('		      %s - Added %i - Update %i - Delete %i',10,1,'AuditEventType', @AddCount_AET, @UpdateCount_AET, @DeleteCount_AET) WITH NOWAIT;

