
GO
ALTER ROLE [DataViewer] ADD MEMBER [User_DSCI];
GO
ALTER ROLE [DataViewer] ADD MEMBER [EAS1920_RO_User];
GO
ALTER ROLE [DataProcessor] ADD MEMBER [EAS1920_RW_User];
GO
ALTER ROLE [DataProcessor] ADD MEMBER [EAS1920_RW_User];
